"""Functional public interface and compatibility dispatch.

This module is a thin re-export facade. The implementation now lives in the
``magpylib_jax.fields`` package (``api``, ``prepare``, ``cache``, ``engine`` and
``eager`` submodules). Every historical ``from magpylib_jax.functional import X``
and ``functional.X`` access keeps resolving through the re-exports below.
"""

from __future__ import annotations

from magpylib_jax.fields.api import (
    _ALIASES,
    _SOURCE_TYPE_IDS,
    _SOURCE_TYPE_ORDER,
    _SUPPORTED_PIXEL_AGGS,
    _apply_squeeze,
    _check_getbh_output_type,
    _check_pixel_agg,
    _compute_field,
    _has_tracer,
    _is_array_like,
    _normalize_source_type,
    _pad_axis0,
    _pad_path,
    getB,
    getH,
    getJ,
    getM,
)
from magpylib_jax.fields.cache import (
    _SENSOR_PREP_CACHE,
    _SENSOR_PREP_CACHE_MAX,
    _SOURCE_PREP_CACHE,
    _SOURCE_PREP_CACHE_MAX,
    _lru_get,
    _lru_put,
    _sensor_prep_cache_key,
    _source_prep_cache_key,
)
from magpylib_jax.fields.eager import (
    _compute_field_legacy,
    _evaluate_core_field,
    _evaluate_source_field,
    _get_field_from_type,
)
from magpylib_jax.fields.engine import (
    _apply_pixel_agg_masked,
    _compute_field_jit,
    _compute_field_jit_core,
    _compute_field_jit_core_compiled,
    _is_all_right_handed,
    _is_identity_rotation_stack,
    _safe_static_bool,
    _segment_sum,
)
from magpylib_jax.fields.prepare import (
    _MAX_SOURCE_CHUNK_SIZE,
    _build_source_specs,
    _format_observers,
    _format_source_groups,
    _pad_sources_for_chunking,
    _prepare_sensors_jit,
    _prepare_sources_jit,
    _select_source_chunk_size,
    _source_kwargs_from_object,
    _source_label,
    _stack_padded_paths,
    _stack_singleton_paths,
)

__all__ = [
    "getB",
    "getH",
    "getJ",
    "getM",
    "_compute_field",
    "_compute_field_jit",
    "_compute_field_jit_core",
    "_compute_field_jit_core_compiled",
    "_compute_field_legacy",
    "_evaluate_core_field",
    "_evaluate_source_field",
    "_get_field_from_type",
    "_apply_pixel_agg_masked",
    "_apply_squeeze",
    "_build_source_specs",
    "_prepare_sources_jit",
    "_prepare_sensors_jit",
    "_format_observers",
    "_format_source_groups",
    "_source_kwargs_from_object",
    "_source_label",
    "_stack_padded_paths",
    "_stack_singleton_paths",
    "_pad_sources_for_chunking",
    "_select_source_chunk_size",
    "_segment_sum",
    "_is_identity_rotation_stack",
    "_is_all_right_handed",
    "_safe_static_bool",
    "_normalize_source_type",
    "_check_getbh_output_type",
    "_check_pixel_agg",
    "_is_array_like",
    "_has_tracer",
    "_pad_path",
    "_pad_axis0",
    "_lru_get",
    "_lru_put",
    "_source_prep_cache_key",
    "_sensor_prep_cache_key",
    "_ALIASES",
    "_SOURCE_TYPE_ORDER",
    "_SOURCE_TYPE_IDS",
    "_SUPPORTED_PIXEL_AGGS",
    "_MAX_SOURCE_CHUNK_SIZE",
    "_SOURCE_PREP_CACHE",
    "_SOURCE_PREP_CACHE_MAX",
    "_SENSOR_PREP_CACHE",
    "_SENSOR_PREP_CACHE_MAX",
]
